# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('das', '0006_auto_20180418_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='guid',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='children', to='das.Article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_autor_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_status',
            field=models.CharField(choices=[('1', 'publish'), ('2', 'close'), ('3', 'inherit')], default='1',
                                   max_length=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='das.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
