# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0008_auto_20180507_0024'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='comment',
        #     name='comment_autor',
        # ),
        # migrations.AddField(
        #     model_name='article',
        #     name='guid',
        #     field=models.URLField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='comment',
        #     name='comment_author',
        #     field=models.CharField(default=0, max_length=30),
        #     preserve_default=False,
        # ),
    ]
