# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0009_auto_20180507_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_status',
            field=models.CharField(choices=[('1', 'open'), ('2', 'close')], default='2', max_length=1),
        ),
    ]
