# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-09 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('das', '0010_auto_20180507_1054'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='comment',
        #     name='comment_autor_ip',
        # ),

    ]
