# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('das', '0015_auto_20180515_1738'),
    ]

    operations = [
        #     migrations.RenameField(
        #         model_name='comment',
        #         old_name='comment_autor',
        #         new_name='comment_author',
        #     ),
        #     migrations.RemoveField(
        #         model_name='article',
        #         name='article_mime_type',
        #     ),
        #     migrations.AddField(
        #         model_name='article',
        #         name='guid',
        #         field=models.URLField(blank=True, null=True),
        #     ),
    ]
