# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-27 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('das', '0018_auto_20180527_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likecommentship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='like_user',
        ),
        migrations.AddField(
            model_name='user',
            name='like_comment',
            field=models.ManyToManyField(related_name='comment_like_user', through='das.Likecommentship',
                                         to='das.Comment'),
        ),
    ]
