# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-27 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('das', '0019_auto_20180527_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likearticleship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='like_article',
            field=models.ManyToManyField(related_name='article_like_user', through='das.Likearticleship',
                                         to='das.Article'),
        ),
    ]
