# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0020_auto_20180527_2137'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='article',
        #     name='article_mime_type',
        # ),
        # migrations.RemoveField(
        #     model_name='comment',
        #     name='comment_autor',
        # ),
        # migrations.AddField(
        #     model_name='article',
        #     name='guid',
        #     field=models.URLField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='comment',
        #     name='comment_author',
        #     field=models.CharField(default=0, max_length=30),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='/static/assets/avatars/avatar.png', upload_to='static/assets/avatars/'),
        ),
    ]
