# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-02 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0021_auto_20180528_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitemeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100, null=True)),
                ('keywords', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100, null=True)),
                ('subtitle', models.CharField(max_length=100, null=True)),
                ('announcement', models.CharField(max_length=50, null=True)),
                ('favicon', models.CharField(max_length=100, null=True)),
                ('head_background_img', models.CharField(default='static/assets/img/1.jpg', max_length=100)),
                ('author_img', models.CharField(max_length=100, null=True)),
                ('head_code', models.CharField(max_length=1000, null=True)),
                ('foot_code', models.CharField(max_length=1000, null=True)),
                ('is_weibo', models.CharField(default='0', max_length=1)),
                ('wb_uid', models.CharField(max_length=15, null=True)),
                ('is_wechat', models.CharField(default='0', max_length=1)),
                ('wechat_qrcode', models.CharField(max_length=100, null=True)),
                ('is_qqgroup', models.CharField(default='0', max_length=1)),
                ('qqgroup_url', models.CharField(max_length=500, null=True)),
                ('is_twitter', models.CharField(default='0', max_length=1)),
                ('twitter_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        # migrations.RenameField(
        #     model_name='comment',
        #     old_name='comment_autor',
        #     new_name='comment_author',
        # ),
        # migrations.RemoveField(
        #     model_name='article',
        #     name='article_mime_type',
        # ),
        # migrations.AddField(
        #     model_name='article',
        #     name='guid',
        #     field=models.URLField(blank=True, null=True),
        # ),
    ]
