# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-09 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0022_auto_20181102_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('o_file_name', models.CharField(max_length=100)),
                ('file_local_path', models.CharField(max_length=200)),
                ('file_url', models.CharField(max_length=300)),
                ('file_type', models.CharField(max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mediaship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # migrations.RenameField(
        #     model_name='comment',
        #     old_name='comment_autor',
        #     new_name='comment_author',
        # ),
        # migrations.RemoveField(
        #     model_name='article',
        #     name='article_mime_type',
        # ),
        # migrations.AddField(
        #     model_name='article',
        #     name='guid',
        #     field=models.URLField(blank=True, null=True),
        # ),
        migrations.AddField(
            model_name='mediaship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.Article'),
        ),
        migrations.AddField(
            model_name='mediaship',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.Media'),
        ),
        migrations.AddField(
            model_name='media',
            name='members',
            field=models.ManyToManyField(through='das.Mediaship', to='das.Article'),
        ),
    ]
