# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0025_auto_20181112_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
