# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0026_auto_20181112_1620'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='comment',
        #     old_name='comment_autor',
        #     new_name='comment_author',
        # ),
        # migrations.RemoveField(
        #     model_name='article',
        #     name='article_mime_type',
        # ),
        # migrations.AddField(
        #     model_name='article',
        #     name='guid',
        #     field=models.URLField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='sitemeta',
            name='author_img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='favicon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='foot_code',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='head_code',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='wechat_qrcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
