# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('das', '0028_auto_20181210_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_ptr',
        ),
        # migrations.RenameField(
        #     model_name='comment',
        #     old_name='comment_autor',
        #     new_name='comment_author',
        # ),
        # migrations.RemoveField(
        #     model_name='article',
        #     name='article_mime_type',
        # ),
        # migrations.AddField(
        #     model_name='article',
        #     name='guid',
        #     field=models.URLField(blank=True, null=True),
        # ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
