# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('das', '0029_auto_20181210_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={'permissions': (
            ('access_dashboard', '\u666e\u901a\u7ba1\u7406\u5458'), ('access_all', '\u8d85\u7ea7\u7ba1\u7406\u5458'),
            ('access_member', '\u666e\u901a\u4f1a\u5458'))},
        ),
        # migrations.RenameField(
        #     model_name='comment',
        #     old_name='comment_autor',
        #     new_name='comment_author',
        # ),
        # migrations.RemoveField(
        #     model_name='article',
        #     name='article_mime_type',
        # ),
        # migrations.AddField(
        #     model_name='article',
        #     name='guid',
        #     field=models.URLField(blank=True, null=True),
        # ),
    ]
