# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-12 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('das', '0031_auto_20190209_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=30, unique=True)),
                ('menu_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=30)),
                ('option_title', models.CharField(max_length=30, null=True)),
                ('option_value', models.CharField(max_length=2000, null=True)),
                ('option_icon', models.CharField(max_length=30, null=True)),
                ('option_level', models.IntegerField(default=1)),
                ('menu',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='das.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_option_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=30)),
                ('option_value', models.CharField(max_length=2000, null=True)),
            ],
        ),
        # migrations.RenameField(
        #     model_name='comment',
        #     old_name='comment_autor',
        #     new_name='comment_author',
        # ),
        # migrations.RemoveField(
        #     model_name='article',
        #     name='article_mime_type',
        # ),
        # migrations.AddField(
        #     model_name='article',
        #     name='guid',
        #     field=models.URLField(blank=True, null=True),
        # ),
    ]
