# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-12 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Menu_option_template = apps.get_model("das", "Menu_option_template")
        db_alias = schema_editor.connection.alias
        Menu_option_template.objects.using(db_alias).bulk_create([
            Menu_option_template(option_name=u'登录框',
                                 option_value="<div class=\"col-md-3\" style=\"padding-top: 30px;\"><div class=\"widget-box  widget\"><div class=\"widget-header\"><span class=\"icon\"><i class=\"icon-list\"></i></span>| {% if request.user.pk %}用户信息{% else %}登录{% endif %}</div><div class=\"widget-body padding-4\"><div class=\"widget-main\"><p class=\"center\">{% if request.user.pk %}欢迎光临<br><a href=\"{% url 'user_show' request.user.pk 1 %}\">{{ request.user.username }}</a><br><img src=\"{{ request.user.avatar }}\" width=\"50\" height=\"50\"><br><a href=\"{% url 'das_index' %}\">管理</a><a href=\"{% url 'logout' %}\">登出</a>{% else %}<form class=\"form-horizontal\" action=\"{% url 'login' %}\" method=\"post\">{% csrf_token %}用户名：<input  type=\"text\" id=\"username\" name=\"username\" placeholder=\"用户名\"><br><br>密&nbsp &nbsp&nbsp码：<input  type=\"password\" id=\"password\" name=\"password\" placeholder=\"******\"><br><br><p class=\"center\"><button class=\"btn btn-danger\" type=\"submit\">登录</button> <a href=\"{% url 'register' %}\" class=\"btn btn-info\">注册</a></p></form>{% endif %}</p></div></div></div>")
        ])

    def reverse_func(apps, schema_editor):
        Menu_option_template = apps.get_model("das", "Menu_option_template")
        db_alias = schema_editor.connection.alias
        Menu_option_template.objects.using(db_alias).filter(option_name=u'登录框').delete()

    dependencies = [
        ('das', '0032_auto_20190212_2154'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
