# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-12 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Menu = apps.get_model("das", "Menu")
        db_alias = schema_editor.connection.alias
        Menu.objects.using(db_alias).bulk_create([
            Menu(menu_name=u'默认右侧边栏', menu_type="tool")
        ])

    def reverse_func(apps, schema_editor):
        Menu = apps.get_model("das", "Menu")
        db_alias = schema_editor.connection.alias
        Menu.objects.using(db_alias).filter(menu_name=u'默认右侧边栏').delete()

    dependencies = [
        ('das', '0033_auto_20190212_2241'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
