# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-19 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Menu_option_template = apps.get_model("das", "Menu_option_template")
        db_alias = schema_editor.connection.alias
        Menu_option_template.objects.using(db_alias).bulk_create([
            Menu_option_template(option_name=u'站内搜索', option_value="index/tool_template/search_temp.html"),
        ])

    def reverse_func(apps, schema_editor):
        Menu_option_template = apps.get_model("das", "Menu_option_template")
        db_alias = schema_editor.connection.alias
        Menu_option_template.objects.using(db_alias).filter(option_name=u'站内搜索').delete()

    dependencies = [
        ('das', '0039_auto_20190218_2018'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
