# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-22 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Menu_position = apps.get_model("das", "Menu_position")
        db_alias = schema_editor.connection.alias
        Menu_position.objects.using(db_alias).bulk_create([
            Menu_position(position=u'顶部主菜单'),
            Menu_position(position=u'底部友链'),
        ])

    def reverse_func(apps, schema_editor):
        Menu_position = apps.get_model("das", "Menu_position")
        db_alias = schema_editor.connection.alias
        Menu_position.objects.using(db_alias).filter(position=u'顶部主菜单').delete()
        Menu_position.objects.using(db_alias).filter(position=u'底部友链').delete()

    dependencies = [
        ('das', '0041_auto_20190221_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='menu_option',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='children', to='das.Menu_option'),
        ),
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='menu_position', to='das.Menu_position'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
