# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-25 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Menu_position = apps.get_model("das", "Menu_position")
        db_alias = schema_editor.connection.alias
        Menu_position.objects.using(db_alias).bulk_create([
            Menu_position(position=u'底部菜单'),
        ])

    def reverse_func(apps, schema_editor):
        Menu_position = apps.get_model("das", "Menu_position")
        db_alias = schema_editor.connection.alias
        Menu_position.objects.using(db_alias).filter(position=u'底部菜单').delete()

    dependencies = [
        ('das', '0043_auto_20190223_2150'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
